apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-nfs
spec:
  storageClassName: prometheus
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/k8s/prometheus
    server: 127.0.0.1