apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-nfs
spec:
  storageClassName: grafana
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/k8s/grafana
    server: 127.0.0.1