apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-grafana
  namespace: monitoring
spec:
  storageClassName: grafana
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi