apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-promo
  namespace: monitoring
spec:
  storageClassName: prometheus
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi